---
# tasks file for roles/metallb
- name: prerequisites
  apt:
    name: python3-pip
    state: present
  when: groups['bootstrap'] | length  == 1

- name: Replace pip per apt
  apt:
    name: "{{ pip_packages }}"
    state: present
  when: groups['bootstrap'] | length  == 1

- name: Install Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  when: groups['bootstrap'] | length  == 1

# - name: Install helm if not exists
#   unarchive:
#     src: "https://get.helm.sh/helm-v{{ addons_helm_version }}-linux-amd64.tar.gz"
#     dest: /usr/local/bin
#     extra_opts: "--strip-components=1"
#     owner: root
#     group: root
#     mode: 0755
#     remote_src: true
#   args:
#     creates: /usr/local/bin/helm
#   when: groups['bootstrap'] | length  == 1

- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    state: present
  tags:
    - helm
  when: groups['bootstrap'] | length  == 1

- name: Add stable Metallb chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
  when: groups['bootstrap'] | length  == 1

- name: Install metallb
  kubernetes.core.helm:
    name: metallb-system
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
  when: groups['bootstrap'] | length  == 1

- name: Wait until install done
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app.kubernetes.io/name=metallb
    wait: true
    namespace: metallb-system
    wait_sleep: 5
    wait_timeout: 150
  when: groups['bootstrap'] | length  == 1

- name: Apply the configuration
  kubernetes.core.k8s:
    namespace: metallb-ingress
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default
        namespace: metallb-system
      spec:
        addresses:
          - "{{ prefix }}.229/32"
          - "{{ prefix }}.230/32"
          - "{{ prefix }}.231/32"
  when: groups['bootstrap'] | length  == 1

- name: Apply the advertisement
  kubernetes.core.k8s:
    namespace: metallb-ingress
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2advertisement1
        namespace: metallb-system
      spec:
        ipAddressPools:
          - default
  when: groups['bootstrap'] | length  == 1
