#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible/roles/bsd
packages:
  - bastille
  - sbcl
  - emacs-nox
  - doas
  - tree
  - git-lite
  - htop

account: spike spiegel
email: spike@gmail.com
emacs_home: /home/spike/.emacs.d

bastille_release: "15.0-RELEASE"

ext_if: "eth0"

admin_ip: "10.9.0.30"

jails:
  - name: "jail-hls"
    address: "10.0.0.10/24"
    packages: ["nginx"]
    ports: ["80", "443"]
