---
- name: Install Pixie prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Install Pixie Cloud
  ansible.builtin.include_tasks: cloud.yml

- name: Configure Pixie DNS
  ansible.builtin.include_tasks: coredns.yml

- name: Install Pixie Vizier
  ansible.builtin.include_tasks: vizier.yml
