all:
  children:
    main_cluster:
      children:
        bootstrap:
          hosts:
%{ for master in masters ~}
%{ if substr(master.address,-3,-1) == "101" ~}
            ${master.hostname}:
              ansible_host: ${master.address}
              ansible_hostname: ${master.hostname}
%{ endif ~}
%{ endfor ~}
        master_nodes:
          hosts:
%{ for master in masters ~}
%{ if substr(master.address,-3,-1) != "101" ~}
            ${master.hostname}:
              ansible_host: ${master.address}
              ansible_hostname: ${master.hostname}
%{ endif ~}
%{ endfor ~}
        worker_nodes:
          hosts:
%{ for worker in workers ~}
            ${worker.hostname}:
              ansible_host: ${worker.address}
              ansible_hostname: ${worker.hostname}
%{ endfor ~}
  vars:
    ansible_user: ${userctn}
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ${privkeyctn}
