#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/videos

- name: Waiting for SSH
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 300
    sleep: 5

- name: Download films
  get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bastille/jails/{{ item.jail }}/root/var/www/videos/hls/{{ item.name }}.mov"
  loop: "{{ videos }}"

- name: Copy Exec
  template:
    src: create-vod-hls.sh.j2
    dest: "/usr/local/bastille/jails/{{ item.jail }}/root/var/www/videos/hls/create-vod-hls.sh"
  loop: "{{ videos }}"

- name: Execute script
  command:
  args:
    chdir: "/usr/local/bastille/jails/{{ item.jail }}/root/var/www/videos/hls"
    cmd: |
      bash /usr/local/bastille/jails/{{ item.jail }}/root/var/www/videos/hls/create-vod-hls.sh /usr/local/bastille/jails/{{ item.jail }}/root/var/www/videos/hls/{{ item.name }}.mov
  loop: "{{ videos }}"
