#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/videos

- name: Waiting for SSH
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 300
    sleep: 5

- name: Download films
  ansible.builtin.get_url:
    url: "{{ item.1.url }}"
    dest: "/usr/local/bastille/jails/{{ item.0.jail }}/root/var/www/videos/hls/{{ item.1.name }}.mov"
    mode: "0644"
  loop: "{{ videos | subelements('videos') }}"

- name: Copy Exec
  ansible.builtin.template:
    src: create-vod-hls.sh.j2
    dest: "/usr/local/bastille/jails/{{ item.0.jail }}/root/var/www/videos/hls/create-vod-hls.sh"
    mode: "0755"
  loop: "{{ videos | subelements('videos') }}"

- name: Execute script
  ansible.builtin.command:
    cmd: "./create-vod-hls.sh {{ item.1.name }}.mov"
    chdir: "/usr/local/bastille/jails/{{ item.0.jail }}/root/var/www/videos/hls"
  loop: "{{ videos | subelements('videos') }}"
