#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible/roles/storage
packages:
  - bastille

bastille_interface: "eth0"
bastille_release: "15.0-RELEASE"

jails:
  - name: nfs
    octet: "210"
    packages:
      - htop
      - tree
    services:
      - nfsd
      - mountd
      - rpcbind
    ports:
      - port: 2049
        proto: tcp
      - port: 111
        proto: udp
  - name: dns
    octet: "211"
    packages:
      - htop
      - bind920
    services:
      - named
    ports:
      - port: 953
        proto: tcp

accounts:
  - name: spike
    uid: 1010
    gid: 1010
  - name: faye
    uid: 1020
    gid: 1020

new_groups:
  - name: crew
    gid: 1030
  - name: spike
    gid: 1010
  - name: faye
    gid: 1020
