---
- name: install registry
  hosts: all
  become: true

  vars:
    hostname: "${name}"
    prefix: "${prefix}"
    subnet: "${prefix}.0"
    admin_ip: "${admin-ip}"
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  environment:
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  roles:
    - registry
