#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/frontend
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Clone Yano branch
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ yano_home }}"
    single_branch: yes
    version: main
  become: true
  become_user: spike

- name: Ensure quicklisp directory exists
  ansible.builtin.file:
    path: "{{ quicklisp_home }}"
    state: directory
    owner: spike
    group: spike
    mode: "0755"

- name: Download quicklisp bootstrap
  ansible.builtin.get_url:
    url: "{{ quicklisp_url }}"
    dest: "{{ quicklisp_bootstrap }}"
    mode: "0644"

- name: Install Quicklisp (SBCL) non-interactively
  ansible.builtin.command: >
    {{ lisp_cmd }}
    --noinform
    --non-interactive
    --load {{ quicklisp_bootstrap }}
    --eval '(quicklisp-quickstart:install :path "{{ quicklisp_home }}/")'
    --quit
  become: true
  become_user: spike
  args:
    creates: "{{ quicklisp_home }}/setup.lisp"

- name: Ensure SBCL system rc exists
  ansible.builtin.file:
    path: "{{ sbcl_system_rc }}"
    state: touch
    owner: spike
    group: spike
    mode: "0644"

- name: Add Quicklisp autoload to /etc/sbclrc
  ansible.builtin.blockinfile:
    path: "{{ sbcl_system_rc }}"
    marker: ";; {mark} ANSIBLE MANAGED QUICKLISP"
    block: |
      ;;; The following lines added by ql:add-to-init-file:
      #-quicklisp
      (let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                             (user-homedir-pathname))))
        (when (probe-file quicklisp-init)
           (load quicklisp-init)))

      (setf sb-impl::*default-external-format* :utf-8)

- name: Ensure quicklisp directory exists
  ansible.builtin.file:
    path: "{{ emacs_home }}"
    state: directory
    owner: spike
    group: spike
    mode: "0755"

- name: Copy init.el
  ansible.builtin.template:
    src: init.el.j2
    dest: "{{ emacs_home }}/init.el"
    owner: spike
    group: spike
    mode: "0644"

- name: Create systemd user
  ansible.builtin.file:
    path: "{{ systemd_user }}"
    state: directory
    owner: spike
    group: spike
    mode: "0755"

- name: Copy template
  ansible.builtin.template:
    src: emacs.service.j2
    dest: "{{ systemd_user }}/emacs.service"

- name: Enable lingering for spike
  become: true
  command: loginctl enable-linger spike

- name: Get spike uid
  command: id -u spike
  register: spike_uid
  changed_when: false

- name: Daemon reload
  command: systemctl --user daemon-reload
  become: true
  become_user: spike
  tags: emacs

- name: Enable service
  command: systemctl --user enable emacs
  become: true
  become_user: spike
  tags: emacs

- name: Start service
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ spike_uid.stdout }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ spike_uid.stdout }}/bus"
  command: systemctl --user start emacs
  become: true
  become_user: spike
  tags: emacs

- name: Add bash
  command: echo 'alias e="emacsclient -t -a \"\""' >> ~/.bashrc
  become: true
  become_user: spike
