#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/storage
- name: Set runtime hostname
  ansible.builtin.command: hostname {{ hostname }}

- name: Persist hostname in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: "^hostname="
    line: 'hostname="{{ hostname }}"'
    create: yes

- name: Install bastille and more
  community.general.pkgng:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Enable bastille at boot
  community.general.sysrc:
    name: bastille_enable
    value: "YES"

- name: Clone interface
  ansible.builtin.shell: /usr/sbin/sysrc cloned_interfaces+=lo1

- name: Name interface
  community.general.sysrc:
    name: ifconfig_lo1_name
    value: "bastille0"

- name: Start service
  ansible.builtin.shell: /usr/sbin/service netif cloneup
  register: result_service

- name: Bootstrap Bastille release
  command: bastille bootstrap {{ bastille_release }}
  args:
    creates: "/usr/local/bastille/releases/{{ bastille_release }}"

# - name: Create jails
#   ansible.builtin.command: >
#     bastille create {{ item.name }} {{ bastille_release }} {{ prefix}}.{{ item.octet }}
#   args:
#     creates: "/usr/local/bastille/jails/{{ item.name }}"
#   loop: "{{ jails }}"

- name: Create jail
  ansible.builtin.shell: "bastille create {{ item.name }} {{ bastille_release }}  {{ prefix }}.{{ item.octet }} {{ bastille_interface }}"
  with_items: "{{ jails }}"
  args:
    creates: "/usr/local/bastille/jails/{{ item.name }}"

- name: Add proxy pkg
  ansible.builtin.blockinfile:
    path: /usr/local/etc/pkg.conf
    block: |
      PKG_ENV: {
        HTTP_PROXY  : "{{ http_proxy }}"
        HTTPS_PROXY : "{{ https_proxy }}"
      }
    append_newline: true
    prepend_newline: true

- name: Create directory pk
  file:
    path: "/usr/local/bastille/jails/{{ item.name }}/root/usr/local/etc"
    state: directory
    recurse: yes
  loop: "{{ jails }}"

- name: Add proxy pkg
  ansible.builtin.blockinfile:
    path: "/usr/local/bastille/jails/{{ item.name }}/root/usr/local/etc/pkg.conf"
    block: |
      PKG_ENV: {
        HTTP_PROXY  : "{{ http_proxy }}"
        HTTPS_PROXY : "{{ https_proxy }}"
      }
    create: true
  loop: "{{ jails }}"

- name: Update jail
  ansible.builtin.shell: "bastille cmd {{ item.name }} env ASSUME_ALWAYS_YES=yes pkg update "
  with_items: "{{ jails }}"

- name: Add packages
  ansible.builtin.command: "bastille pkg {{ item.0.name }} install -y {{ item.1 }}"
  loop: "{{ jails | subelements('packages') }}"

- name: Enable packages in jail
  ansible.builtin.shell: >
    bastille sysrc {{ item.0.name }} {{item.1}}_enable=YES
  loop: "{{ jails | subelements('services') }}"

- name: Deploy pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: "0644"

######################################
# NFS CONFIGURATION
######################################

- name: Get nfs jail
  set_fact:
    nfs_jail: "{{ jails | selectattr('name', 'equalto', 'nfs') | first }}"

- name: Create NFS directory
  file:
    path: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/nfs"
    owner: 0
    group: 0
    mode: "0755"
    state: directory
  when: nfs_jail is defined

- name: Check if group exists
  command: >
    bastille cmd {{ nfs_jail.name }} pw groupshow {{ item.name }}
  register: group_check
  failed_when: false
  changed_when: false
  loop: "{{ new_groups }}"
  when: nfs_jail is defined

- name: Add groups from accounts in nfs jail
  command: >
    bastille cmd {{ nfs_jail.name }} pw groupadd -n {{ item.item.name }} -g {{ item.item.gid }}
  loop: "{{ group_check.results }}"
  when:
    - nfs_jail is defined
    - item.rc != 0

- name: Check if user exists
  command: >
    bastille cmd {{ nfs_jail.name }} pw usershow {{ item.name }}
  register: user_check
  failed_when: false
  changed_when: false
  loop: "{{ accounts }}"
  when: nfs_jail is defined

- name: Add users in nfs jail
  command: >
    bastille cmd {{ nfs_jail.name }} pw useradd -n {{ item.item.name }}
    -u {{ item.item.uid }}
    -g {{ item.item.gid }}
    -G crew,wheel
    -c "{{ item.item.name }}"
    -m
    -s /bin/tcsh
  loop: "{{ user_check.results }}"
  when:
    - nfs_jail is defined
    - item.rc != 0

- name: Create home directories
  file:
    path: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/nfs/{{ item.name }}"
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    mode: "0700"
    state: directory
  loop: "{{ accounts }}"
  when: nfs_jail is defined

- name: Get crew info
  set_fact:
    crew_id: "{{ new_groups | selectattr('name', 'equalto', 'crew') | first }}"

- name: Create common directory
  file:
    path: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/nfs/crew"
    owner: root
    group: "{{ crew_id.gid }}"
    mode: "0770"
    state: directory
  when:
    - nfs_jail is defined
    - crew_id is defined

- name: Deploy exports
  template:
    src: exports.j2
    dest: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/etc/exports"
    owner: root
    group: wheel
    mode: "0644"
  when: nfs_jail is defined

- name: Restart services in nfs jail
  ansible.builtin.command: >
    bastille service {{ nfs_jail.name }} {{ item }} restart
  loop: "{{ nfs_jail.services }}"
  when: nfs_jail is defined

######################################
# PF CONFIGURATION
######################################

- name: Check if pf module is loaded
  command: kldstat -n pf
  register: pf_loaded
  failed_when: false
  changed_when: false

- name: Load pf module if not loaded
  command: kldload pf
  when: pf_loaded.rc != 0

- name: check pf.conf
  command: pfctl -vnf /etc/pf.conf
  register: pf_check
  changed_when: false

- name: reload pf
  command: pfctl -f /etc/pf.conf
  when: pf_check.rc == 0
  notify: reload pf

######################################
# PF CONFIGURATION
######################################

- name: Configure tcsh prompt
  ansible.builtin.lineinfile:
    path: "/usr/local/bastille/jails/{{ nfs_jail.name }}/root/home/{{ item.name }}/.cshrc"
    regexp: '^\s*set\s+prompt\s*=.*'
    line: '	set prompt="%{\033[0m%}\n%{\033[0;32m%}%n@%m%{\033[0m%}:%{\033[0;33m%}%~%{\033[0m%} %# "'
    create: true
  loop: "{{ accounts }}"
  when: nfs_jail is defined
