#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible/roles/hoover
- name: Wait for kubeconfig
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 60

- name: Set kubeconfig env
  set_fact:
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Wait for Kubernetes API
  command: kubectl get nodes
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: result
  retries: 10
  delay: 5
  until: result.rc == 0

- name: Verify cluster access
  command: kubectl get nodes
  changed_when: false

- name: Verify NFS StorageClass exists
  command: kubectl get storageclass {{ storage_class }}
  changed_when: false

- name: Create monitoring namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Namespace
    name: "{{ monitoring_namespace }}"
    state: present

- name: Add Helm repos
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop: "{{ repos }}"

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'templates/values-prometheus.yml.j2') | from_yaml }}"
    wait: true
    timeout: 10m

- name: Verify Prometheus stack pods
  command: kubectl -n {{ monitoring_namespace }} get pods
  changed_when: false
  tags:
    - step1

- name: Vérifier que la CRD ServiceMonitor existe
  command: kubectl get crd servicemonitors.monitoring.coreos.com
  register: servicemonitor_crd
  changed_when: false
  failed_when: servicemonitor_crd.rc != 0

- name: Upgrade Cilium and Hubble metrics
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    create_namespace: false
    reuse_values: true
    update_repo_cache: true
    values: "{{ lookup('template', 'templates/values-cilium-metrics.yml.j2') | from_yaml }}"
    wait: true
    timeout: 10m
  when: inventory_hostname in groups['bootstrap']

- name: Vérifier les ServiceMonitor Cilium/Hubble
  command: kubectl get servicemonitor -A
  register: cilium_servicemonitors
  changed_when: false

- name: Afficher les ServiceMonitor Cilium/Hubble
  debug:
    msg: "{{ cilium_servicemonitors.stdout_lines | select('search', 'cilium|hubble') | list }}"

- name: Redémarrer Cilium pour appliquer proprement les métriques
  command: kubectl -n kube-system rollout restart daemonset/cilium
  changed_when: true

- name: Attendre que Cilium soit prêt
  command: kubectl -n kube-system rollout status daemonset/cilium --timeout=180s
  changed_when: false

- name: Deploy Loki
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: loki
    chart_ref: grafana/loki
    chart_version: "6.42.0"
    release_namespace: "{{ monitoring_namespace }}"
    values: "{{ lookup('template', 'templates/values-loki.yml.j2') | from_yaml }}"
    wait: true
    timeout: 10m

- name: Deploy Alloy
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: alloy
    chart_ref: grafana/alloy
    release_namespace: "{{ monitoring_namespace }}"
    values: "{{ lookup('template', 'templates/values-alloy.yml.j2') | from_yaml }}"
    wait: true
    timeout: 10m

- name: Deploy Tempo
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: tempo
    chart_ref: grafana/tempo
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'templates/values-tempo.yml.j2') | from_yaml }}"
    wait: true
    timeout: 20m

# - name: Deploy OpenTelemetry Collector
#   kubernetes.core.helm:
#     kubeconfig: "{{ kubeconfig }}"
#     name: otel-collector
#     chart_ref: open-telemetry/opentelemetry-collector
#     release_namespace: "{{ monitoring_namespace }}"
#     values: "{{ lookup('template', 'templates/values-otel.yml.j2') | from_yaml }}"
#     wait: true
#   tags:
#     - step1

- name: Deploy kubernetes-event-exporter
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: kubernetes-event-exporter
    chart_ref: bitnami/kubernetes-event-exporter
    # chart_repo_url: https://charts.bitnami.com/bitnami
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'templates/values-kubernetes-event-exporter.yml.j2') | from_yaml }}"
    wait: true
    timeout: 5m

- name: Final verification
  command: kubectl -n {{ monitoring_namespace }} get pods,pvc,svc
  changed_when: false
