#SPDX-License-Identifier: MIT-0
---
monitoring_namespace: monitoring
storage_class: nfs-client
kubeconfig: /etc/rancher/k3s/k3s.yaml

# Storage
grafana_storage_size: 1Gi #10Gi
prometheus_storage_size: 1Gi #50Gi
alertmanager_storage_size: 1Gi #5Gi
loki_storage_size: 1Gi #50Gi

repos:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
