all:
  children:
    main_cluster:
      children:
        bootstrap:
          hosts:
%{ for server in lisp ~}
            ${server.name}:
              ansible_host: ${server.default_ipv4_address}
              ansible_hostname: ${server.name}
%{ endfor ~}

  vars:
    ansible_user: ${userctn}
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ${privkeyctn}
