---
- name: install LISP
  hosts: all
  become: true
  serial: 1
  vars:
  environment:
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  roles:
    - quicklisp
    - emacs
