variable "area" {}
variable "masters" {}
variable "workers" {}
variable "nbmasters" {}
variable "nbworkers" {}
variable "prefix" {}
variable "userctn" {}
variable "publkeyctn" {}
variable "privkeyctn" {}
variable "vlan" {}
variable "target_node" {}
variable "size" {}
variable "clone" {}
variable "storage" {}
variable "bridge" {}
variable "nameserver" {}
variable "cloudinit" {}
variable "proxy" {}
